Add 'set backupcopy=yes' to vimrc.j2
adfinis-sygroup/ansible-role-console pull request #9
Opened 2019-01-23 14:16 UTC by matthiashuser

##### SUMMARY

##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2019-01-23 15:34 UTC, sliverc approved these changes
LGTM

2019-01-23 15:43 UTC, fujexo commented
I'm not sure if this is good to deploy on every machine?
Can we make this configurable via variable?

2019-01-23 15:56 UTC, fujexo requested changes

2019-01-23 15:56 UTC, fujexo commented on templates/etc/vimrc.j2
> +set backupcopy=yes
Please make `backupcopy` configurable using a variable. The default should be without `backupcopy` set to `yes`.
We can then create a group variable for all docker hosts which enables the `backupcopy` on them.

2019-02-26 14:05 UTC, fujexo commented
LGTM

2019-02-26 14:06 UTC, fujexo approved these changes

2019-02-26 14:07 UTC, merged